AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  HereApiKey:
    Type: String
    Description: HERE Location Services API Key (https://developer.here.com/faqs#access-control)

Resources:
  RoutingFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: nodejs12.x
      Handler: routing.routingGET
      Description: 'A lambda function to provide precise instructions to a destination using various transport modes (e.g., car, truck, public transit, bicycle) and leveraging different algorithms (e.g., matrix, isoline routing).'
      Environment:
        Variables:
          HERE_API_KEY: !Ref HereApiKey
      Events:
        GET:
          Type: Api
          Properties:
            Path: /routing/api/{type}/{resourcePath+}
            Method: get
  WaypointSequenceFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: nodejs12.x
      Handler: waypointseq.waypointseqGET
      Description: 'Calculate a list of sequence-optimized waypoints.'
      Environment:
        Variables:
          HERE_API_KEY: !Ref HereApiKey
      Events:
        GET:
          Type: Api
          Properties:
            Path: /waypointseq/api/{resourcePath+}
            Method: get
  CalculateRouteFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: nodejs12.x
      Handler: calculateroutes.calculateRouteGET
      Description: 'Calculates a route using a generic vehicle/pedestrian mode, e.g. car, truck, pedestrian, etc...'
      Environment:
        Variables:
          HERE_API_KEY: !Ref HereApiKey
      Events:
        GET:
          Type: Api
          Properties:
            Path: /calculateRoute/api/{resourcePath+}
            Method: get

Outputs:
  HereApiURL:
    Description: "AWS API Gateway URL for HERE Routing,Waypoint Sequence & CalculateRoutes API."
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"